import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import vm from "node:vm";

test("Pro HTTP flow uses card possession, admin CSRF, manual sync and no upstream request", async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gptc-pro-http-"));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  process.env.DATA_FILE = path.join(dir, "orders.json");
  process.env.ADMIN_TOKEN = "pro-http-local-only";
  process.env.HIFUPAY_API_KEY = "";
  process.env.HIFUPAY_BASE_URL = "http://127.0.0.1:1";
  const { JsonStore } = await import("../src/store.js");
  const store = new JsonStore(process.env.DATA_FILE);
  const card = store.createHCards({ plan: "pro_x20", count: 1 })[0];
  const { server } = await import("../src/server.js");
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}`;
  const json = async (url, body, headers = {}) => {
    const res = await fetch(base + url, { method: "POST", headers: { "Content-Type": "application/json", ...headers }, body: JSON.stringify(body) });
    return { status: res.status, body: await res.json() };
  };
  const login = await fetch(base + "/api/admin/login", { method: "POST", headers: { Origin: "https://www.gptc.cc", "X-Admin-Request": "1", "Content-Type": "application/json" }, body: JSON.stringify({ password: process.env.ADMIN_TOKEN }) });
  assert.equal(login.status, 200);
  const cookie = login.headers.get("set-cookie").split(";")[0];
  const auth = await login.json();
  const admin = { Cookie: cookie, Origin: "https://www.gptc.cc", "X-CSRF-Token": auth.data.csrf };
  const page = await fetch(base + "/admin/pro-orders", { headers: admin });
  assert.equal(page.status, 200);
  assert.match(await page.text(), /Pro 5x 自动充值设置/);
  const recoveryPage = await fetch(base + "/admin/recoveries", { headers: admin });
  assert.equal(recoveryPage.status, 200);
  const recoveryHtml = await recoveryPage.text();
  assert.match(recoveryHtml, /确认充值成功/);
  assert.match(recoveryHtml, /mark-pro-success/);
  assert.match(recoveryHtml, /账号：/);
  const inlineScript = recoveryHtml.match(/<script>([\s\S]*?)<\/script>/)?.[1];
  assert.ok(inlineScript);
  assert.doesNotThrow(() => new vm.Script(inlineScript));
  const deployScript = fs.readFileSync(new URL("../../scripts/deploy-recharge-backend-1panel.mjs", import.meta.url), "utf8");
  assert.match(deployScript, /location = \/admin\/pro-orders \{/);
  assert.match(deployScript, /location \^~ \/admin\/pro-orders\/ \{/);
  assert.equal((await fetch(base + "/api/admin/pro/orders")).status, 401);
  assert.equal((await json("/api/admin/pro/settings", { enabled: true, cardId: "", region: "EG", estimatedChargeUsd: 0, safetyBufferUsd: 0 }, admin)).status, 400);
  const input = { cardInfo: card.code, provider: "czgpt", secretJsonText: JSON.stringify({ userEmail: "test@example.invalid", accessToken: "synthetic", account: { id: "local" } }) };
  const verify = await json("/api/recharge/verify-card", { cardInfo: card.code, provider: "czgpt" });
  assert.equal(verify.body.data.plan, "pro_x20");
  assert.equal(verify.body.data.selectedProvider, "h");
  const first = await json("/api/recharge/confirm", input);
  const second = await json("/api/recharge/confirm", input);
  assert.equal(first.body.data.status, "manual_queued");
  assert.equal(second.body.data.orderId, first.body.data.orderId);
  assert.equal(store.read().orders.length, 1);
  const id = first.body.data.orderId;
  assert.equal((await json("/api/recharge/query-task-status", { orderId: id })).status, 404);
  assert.equal((await fetch(base + "/api/recharge/status/" + id)).status, 404);
  assert.equal((await json("/api/recharge/pro-order-status", { orderId: id, cardInfo: "other" })).status, 404);
  assert.equal((await json("/api/recharge/pro-order-status", { cardInfo: card.code })).body.data.status, "manual_queued");
  const records = await fetch(base + "/api/admin/recharge-records", { headers: admin }).then(res => res.json());
  assert.equal(records.data.pendingCount, 1);
  assert.equal(records.data.records.find(item => item.id === id)?.fulfillmentMode, "manual");
  assert.equal((await json("/api/admin/recoveries/" + id + "/mark-success", {}, admin)).status, 409);
  assert.equal((await json("/api/admin/pro/orders/" + id + "/mark-success", {}, { Cookie: cookie, Origin: "https://www.gptc.cc" })).status, 403);
  const marked = await json("/api/admin/pro/orders/" + id + "/mark-success", { note: "测试人工完成" }, admin);
  assert.equal(marked.status, 200);
  assert.equal((await json("/api/admin/pro/orders/" + id + "/mark-success", {}, admin)).status, 200);
  assert.equal((await json("/api/recharge/pro-order-status", { cardInfo: card.code })).body.data.status, "success");
  assert.equal(store.getHCardByCode(card.code).status, "used");
  assert.equal(store.read().rechargeLogs.filter(item => item.orderId === id && item.step === "pro.admin.mark-success").length, 1);
  const after = await fetch(base + "/api/admin/recharge-records", { headers: admin }).then(res => res.json());
  assert.equal(after.data.pendingCount, 0);
});
