import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import { classifyCreation, recoveryEvidence } from '../src/zzshu-recovery.js';

test('401 distinguishes user authorization from API credentials and uncertain acceptance', () => {
  assert.equal(classifyCreation({status:401,code:401,reasons:{message:'token expired'}}),'token_expired');
  assert.equal(classifyCreation({status:401,code:40107,reasons:{message:'token expired'}}),'channel_unavailable');
  assert.equal(classifyCreation({status:401,code:401,reasons:{message:'API token expired'}}),null);
  assert.equal(classifyCreation({status:401,code:null,reasons:{message:'unauthorized'}}),null);
  assert.equal(classifyCreation({status:400,code:40027,data:{order_no:'already-created'}}),null);
  assert.equal(classifyCreation({status:400,code:40027,data:{payment_result:{status:'failed'}}}),null);
  assert.equal(recoveryEvidence('unlock',{reasonCode:'upstream_success'}),null);
});

test('same-card retry, explicit freezing and audited administrator resolution work through public and admin routes', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(),'zzshu-recovery-actions-'));
  t.after(() => fs.rmSync(dir,{recursive:true,force:true}));
  process.env.DATA_FILE=path.join(dir,'orders.json');
  process.env.ZZSHU_DB_FILE=path.join(dir,'zzshu.sqlite');
  process.env.ZZSHU_ENABLED='true'; process.env.ZZSHU_API_KEY='fixture-key';
  process.env.RECOVERY_ENCRYPTION_KEY='fixture-encryption-key'; process.env.ADMIN_TOKEN='fixture-admin-password';
  const {config}=await import('../src/config.js'); config.zzshuBaseUrl='https://fixture.example.test';
  const {rechargeService:service}=await import('../src/recharge-service.js');
  const {zzshuService:zzs}=await import('../src/zzshu-service.js');
  const {zzshuCredentialStore}=await import('../src/zzshu-credential-store.js');
  const {JsonStore}=await import('../src/store.js');
  const local=new JsonStore(process.env.DATA_FILE);
  let ready=true;
  const originalVerify=zzshuCredentialStore.verifySaved;
  zzshuCredentialStore.verifySaved=async()=>({ok:ready,points:20});
  t.after(()=>{zzshuCredentialStore.verifySaved=originalVerify;});
  await zzs.importCards({text:'4242424242424242,12/40,123',source:'fixture',maxSuccess:10});
  service.updatePlusProvider('zzshu');
  const [expired,uncertain,noNative,apiFailure]=service.createHCards({count:4,source:'fixture'}).data.cards;
  const session={user:{id:'user',email:'user@example.test'},account:{id:'account',planType:'free'},accessToken:'access-old',sessionToken:'session-old',expires:'2040-01-01'};
  let mode='expired',statusMode='processing',directCalls=0;
  const upstream=new Map();
  const realFetch=globalThis.fetch;
  globalThis.fetch=async(url,options)=>{
    if(new URL(url).hostname!=='fixture.example.test') return realFetch(url,options);
    if(new URL(url).pathname.endsWith('/direct')) {
      directCalls++;
      if(mode==='expired') return {ok:false,status:401,json:async()=>({code:401,message:'token expired'})};
      if(mode==='api') return {ok:false,status:401,json:async()=>({code:40107,message:'API key invalid'})};
      if(mode==='network') throw Error('network failed');
      const id='up-'+directCalls,key='query-'+directCalls;
      upstream.set(key,id);
      return {ok:true,status:201,json:async()=>({code:0,data:{order_no:id,card_key:key}})};
    }
    const key=JSON.parse(options.body).cardKey;
    return {ok:true,status:200,json:async()=>({code:0,data:{order_no:upstream.get(key),card_key:key,plan_type:'plus',status:statusMode,
      payment_result:statusMode==='success'?{success:true,status:'paid'}:statusMode==='failed'?{success:false,status:'failed'}:null,is_subscription_cancelled:1}})};
  };
  t.after(()=>{globalThis.fetch=realFetch;});
  const submit=card=>service.confirmRecharge({cardInfo:card.code,secretJsonText:JSON.stringify(session),provider:'zzshu'});
  const first=await submit(expired);
  assert.equal(first.data.status,'failed'); assert.equal(first.data.canRetry,true);
  assert.equal(first.data.actionRequired,'update_session'); assert.match(first.data.message,/授权已失效/);
  assert.equal(/401|ZZS|code/.test(first.data.message),false);
  const firstIntake=local.getOrder(first.data.orderId);
  assert.ok(firstIntake.upstreamTaskId);
  assert.equal(zzs.store.responseHistory(firstIntake.upstreamTaskId).total,1);
  assert.equal(zzs.store.listCards()[0].frozenUses,0);
  assert.equal(local.getHCardByCode(expired.code).status,'unused');
  assert.equal(local.getActiveSubmissionByCode(expired.code),null);
  assert.equal((await service.queryHCardStatus(expired.code,'zzshu')).data.canRetry,true);
  assert.equal((await service.queryTaskStatus({orderId:first.data.orderId})).data.canRetry,true);
  mode='create'; session.accessToken='access-new'; session.sessionToken='session-new';
  let beginCheck,finishCheck;
  const entered=new Promise(resolve=>{beginCheck=resolve;});
  const gate=new Promise(resolve=>{finishCheck=resolve;});
  zzshuCredentialStore.verifySaved=async()=>{beginCheck();await gate;return {ok:true,points:20};};
  const retryPromise=submit(expired);
  await entered;
  const inFlight=local.getActiveSubmissionByCode(expired.code);
  assert.equal(service.applyZzshuDisposition(first.data.orderId,'success',recoveryEvidence('success',{reasonCode:'manual_success'})).ok,false);
  assert.equal(service.applyZzshuDisposition(inFlight.id,'freeze',recoveryEvidence('freeze',{reasonCode:'uncertain'})).ok,false);
  finishCheck();
  const retried=await retryPromise;
  zzshuCredentialStore.verifySaved=async()=>({ok:ready,points:20});
  assert.notEqual(retried.data.orderId,first.data.orderId);
  assert.equal(retried.data.status,'processing'); assert.equal(directCalls,2);
  const nativeId=local.getOrder(retried.data.orderId).upstreamTaskId;
  const submitted=JSON.parse(service.getRecoverySubmission(retried.data.orderId,true).data.submittedJsonText);
  assert.equal(submitted.sessionToken,'session-new');
  assert.equal((await submit(expired)).data.orderId,retried.data.orderId); assert.equal(directCalls,2);
  assert.equal(service.applyZzshuDisposition(first.data.orderId,'unlock',recoveryEvidence('unlock',{reasonCode:'no_charge'})).ok,false);
  statusMode='success'; await service.queryTaskStatus({orderId:retried.data.orderId});
  assert.equal(local.getHCardByCode(expired.code).status,'used');
  assert.equal(zzs.store.listCards()[0].successCount,1);
  assert.equal(service.applyZzshuDisposition(retried.data.orderId,'unlock',recoveryEvidence('unlock',{reasonCode:'no_charge'})).ok,false);
  mode='network'; statusMode='processing';
  const waiting=await submit(uncertain);
  assert.equal(waiting.data.status,'needs_review'); assert.equal(waiting.data.canRetry,false);
  const waitingId=local.getOrder(waiting.data.orderId).upstreamTaskId;
  assert.equal((await submit(uncertain)).data.orderId,waiting.data.orderId); assert.equal(directCalls,3);
  assert.equal((await service.checkZzshuRecovery(waiting.data.orderId)).status,409);
  const {server}=await import('../src/server.js');
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>server.close(resolve)));
  const base=`http://127.0.0.1:${server.address().port}`;
  const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{Origin:'https://www.gptc.cc','Content-Type':'application/json','X-Admin-Request':'1'},body:JSON.stringify({password:'fixture-admin-password'})});
  const cookie=login.headers.get('set-cookie').split(';')[0],csrf=(await login.json()).data.csrf;
  const headers={Cookie:cookie,Origin:'https://www.gptc.cc','X-CSRF-Token':csrf,'Content-Type':'application/json'};
  const action=(id,outcome,reasonCode)=>fetch(`${base}/api/admin/recoveries/${id}/disposition`,{method:'POST',headers,body:JSON.stringify({outcome,reasonCode})});
  assert.equal((await action(waiting.data.orderId,'unlock','upstream_success')).status,400);
  assert.equal((await action(waiting.data.orderId,'freeze','uncertain')).status,200);
  assert.equal(zzs.store.order(waitingId).admin_frozen,1);
  assert.equal(zzs.store.manualCandidate(),undefined);
  assert.equal((await service.queryHCardStatus(uncertain.code,'zzshu')).data.canRecharge,false);
  assert.equal((await action(waiting.data.orderId,'unlock','token_expired')).status,200);
  assert.equal(zzs.store.order(waitingId).retry_allowed,1);
  assert.equal(zzs.store.order(waitingId).use_resolution,'released');
  assert.equal(zzs.store.listCards()[0].frozenUses,0);
  assert.match((await service.queryHCardStatus(uncertain.code,'zzshu')).data.message,/授权已失效/);
  assert.ok(zzs.store.manualCandidate());
  mode='create';
  const renewed=await submit(uncertain);
  assert.equal((await action(waiting.data.orderId,'success','manual_success')).status,409);
  assert.equal((await action(renewed.data.orderId,'freeze','awaiting_support')).status,200);
  statusMode='success'; await service.checkZzshuRecovery(renewed.data.orderId);
  assert.equal((await service.queryTaskStatus({orderId:renewed.data.orderId})).data.status,'needs_review');
  assert.equal((await action(renewed.data.orderId,'success','account_active')).status,200);
  assert.equal((await action(renewed.data.orderId,'success','account_active')).status,409);
  assert.equal(zzs.store.listCards()[0].successCount,2);
  assert.equal(zzs.store.listCards()[0].frozenUses,0);
  // An intake with no upstream task can be manually frozen and released without a replacement card.
  ready=false;
  const prior=await submit(noNative);
  assert.equal(prior.data.canRetry,true); assert.equal(local.getOrder(prior.data.orderId).upstreamTaskId,'');
  local.updateOrder(prior.data.orderId,{status:'needs_review',retryAllowed:false});
  assert.equal((await action(prior.data.orderId,'freeze','account_check')).status,200);
  assert.equal(zzs.store.voucher(noNative.code).status,'frozen');
  assert.equal((await submit(noNative)).data.orderId,prior.data.orderId);
  assert.equal((await action(prior.data.orderId,'unlock','token_expired')).status,200);
  assert.equal((await service.queryHCardStatus(noNative.code,'zzshu')).data.canRetry,true);
  ready=true;mode='api';
  const channel=await submit(apiFailure);
  assert.equal(channel.data.canRetry,true);
  assert.equal(channel.data.actionRequired,'retry');
  assert.equal(/授权已失效|401|ZZS/.test(channel.data.message),false);
  const audit=zzs.store.db.prepare("SELECT reason FROM audit WHERE action='admin_unlock' AND order_id=?").get(waitingId);
  const evidence=JSON.parse(audit.reason);
  assert.match(evidence.operator,/^admin:/); assert.equal(evidence.reasonCode,'token_expired');
  assert.equal(evidence.before,'needs_review'); assert.equal(evidence.after,'failed');
  const html=await fetch(base+'/admin/recoveries',{headers:{Cookie:cookie}}).then(r=>r.text());
  assert.match(html,/recoveryDialog/); assert.match(html,/解锁卡密/); assert.equal(html.includes('window.prompt'),false);
  for(const script of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(script[1]);
  const activate=fs.readFileSync(path.resolve('activate/index.html'),'utf8');
  for(const script of activate.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)) new vm.Script(script[1]);
  assert.match(activate,/使用原卡密，更新 JSON/);
});
