import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const dataFile = process.env.DATA_FILE || path.join(rootDir, "data", "orders.json");

export const config = {
  rootDir,
  host: process.env.HOST || "127.0.0.1",
  port: Number(process.env.PORT || 8788),
  frontendFile: process.env.FRONTEND_FILE || "",
  defaultProvider: process.env.DEFAULT_PROVIDER || "czgpt",
  upstreamBaseUrl: process.env.UPSTREAM_BASE_URL || "https://kkk.ow800.com",
  upstreamAuthToken: process.env.UPSTREAM_AUTH_TOKEN || "",
  upstreamAuthHeader: process.env.UPSTREAM_AUTH_HEADER || "Authorization",
  upstreamAuthScheme: process.env.UPSTREAM_AUTH_SCHEME || "Bearer",
  ayanBaseUrl: process.env.AYAN_BASE_URL || "https://api.987ai.vip",
  ajianBaseUrl: process.env.AJIAN_BASE_URL || "https://ajian.chat",
  ajianSessionTtlMs: Number(process.env.AJIAN_SESSION_TTL_MS || 20 * 60 * 1000),
  ajianUserAgent: process.env.AJIAN_USER_AGENT || "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/139 Safari/537.36",
  resellerBaseUrl: process.env.RESELLER_BASE_URL || "https://666ai.vip",
  xiaoyuBaseUrl: process.env.XIAOYU_BASE_URL || "https://autoserve.de10.online",
  xiaoyuApiKey: process.env.XIAOYU_API_KEY || "",
  hifupayBaseUrl: process.env.HIFUPAY_BASE_URL || "https://sdk.hifupay.com",
  hifupayApiKey: process.env.HIFUPAY_API_KEY || "",
  hifupaySecretFile: process.env.HIFUPAY_SECRET_FILE || path.join(path.dirname(dataFile), "hifupay-api-key.json"),
  hifupayCardId: process.env.HIFUPAY_CARD_ID || "7172",
  hifupayPlan: process.env.HIFUPAY_PLAN || "plus",
  hifupayRegion: process.env.HIFUPAY_REGION || "PH",
  hifupayProxyRegion: process.env.HIFUPAY_PROXY_REGION || "PH3",
  hifupayEngine: process.env.HIFUPAY_ENGINE || "oaics",
  hifupayProStartTimeoutMs: Number(process.env.HIFUPAY_PRO_START_TIMEOUT_MS || 30000),
  hifupayMaxPlusUsers: Number(process.env.HIFUPAY_MAX_PLUS_USERS || 4),
  hifupayUpgradeWindowDays: Number(process.env.HIFUPAY_UPGRADE_WINDOW_DAYS || 30),
  hifupayEstimatedPlusChargeUsd: Number(process.env.HIFUPAY_ESTIMATED_PLUS_CHARGE_USD || 16),
  hifupayEstimatedProChargeUsd: Number(process.env.HIFUPAY_ESTIMATED_PRO_CHARGE_USD || 0),
  hifupaySafetyBufferUsd: Number(process.env.HIFUPAY_SAFETY_BUFFER_USD || 0),
  hifupayPlusMaxBalanceUsd: Number(process.env.HIFUPAY_PLUS_MAX_BALANCE_USD || 66),
  hifupayStaleReservationMinutes: Number(process.env.HIFUPAY_STALE_RESERVATION_MINUTES || 10),
  hifupayFailureConfirmSeconds: Number(process.env.HIFUPAY_FAILURE_CONFIRM_SECONDS || 60),
  hifupayProcessingLookbackHours: Number(process.env.HIFUPAY_PROCESSING_LOOKBACK_HOURS || 168),
  hifupayReconcileIntervalHours: Number(process.env.HIFUPAY_RECONCILE_INTERVAL_HOURS || 24),
  hifupayBalanceToleranceUsd: Number(process.env.HIFUPAY_BALANCE_TOLERANCE_USD || 0.5),
  hifupayProductId: Number(process.env.HIFUPAY_PRODUCT_ID || 3),
  zzshuBaseUrl: process.env.ZZSHU_BASE_URL || "https://card.zzshu.pro",
  // A deployment secret remains supported. The admin-managed secret is kept in
  // a separate encrypted runtime file and is resolved by zzshu-credential-store.
  zzshuApiKey: process.env.ZZSHU_API_KEY || "",
  zzshuSecretFile: process.env.ZZSHU_SECRET_FILE || path.join(path.dirname(dataFile), "zzshu-api-key.json"),
  zzshuEnabled: process.env.ZZSHU_ENABLED === "true",
  zzshuTestMode: process.env.ZZSHU_TEST_MODE === "true",
  zzshuTestVoucherHash: process.env.ZZSHU_TEST_VOUCHER_HASH || "",
  zzshuTestAccountHash: process.env.ZZSHU_TEST_ACCOUNT_HASH || "",
  zzshuTimeoutMs: Number(process.env.ZZSHU_TIMEOUT_MS || 15000),
  zzshuPollMs: Number(process.env.ZZSHU_POLL_MS || 5000),
  zzshuConcurrency: Number(process.env.ZZSHU_CONCURRENCY || 3),
  zzshuFailureThreshold: Number(process.env.ZZSHU_FAILURE_THRESHOLD || 3),
  zzshuDbFile: process.env.ZZSHU_DB_FILE || path.join(path.dirname(dataFile), "zzshu.sqlite"),
  zzshuVaultUrl: process.env.ZZSHU_VAULT_URL || "",
  zzshuVaultToken: process.env.ZZSHU_VAULT_TOKEN || "",
  adminToken: process.env.ADMIN_TOKEN || "",
  hCardQueryMinuteLimit: Number(process.env.H_CARD_QUERY_MINUTE_LIMIT || 10),
  hCardQueryHourLimit: Number(process.env.H_CARD_QUERY_HOUR_LIMIT || 60),
  hSubscriptionSyncLookbackHours: Number(process.env.H_SUBSCRIPTION_SYNC_LOOKBACK_HOURS || 168),
  hSubscriptionFollowUpSeconds: Number(process.env.H_SUBSCRIPTION_FOLLOW_UP_SECONDS || 120),
  adminAlertWebhookUrl: process.env.ADMIN_ALERT_WEBHOOK_URL || "",
  adminAlertWebhookType: process.env.ADMIN_ALERT_WEBHOOK_TYPE || "generic",
  publicBaseUrl: process.env.PUBLIC_BASE_URL || "https://www.gptc.cc",
  recoveryEncryptionKey: process.env.RECOVERY_ENCRYPTION_KEY || "",
  dataFile,
  logFile: process.env.LOG_FILE || path.join(rootDir, "logs", "server.log"),
  defaultProductId: Number(process.env.DEFAULT_PRODUCT_ID || 3),
  pollingIntervalMs: Number(process.env.POLLING_INTERVAL_MS || 4000),
  maxPollingMs: Number(process.env.MAX_POLLING_MS || 120000)
};
